force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class_Size__c.field-meta.xml
<CustomField>
    <fullName>Class_Size__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Class Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class_Meeting_Time__c/Class_Meeting_Time__c.object-meta.xml
<CustomObject>
    <label>Class Meeting Time</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Class Meeting Time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Meeting Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Meeting_Time__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Class for which this record&apos;s days/times are specified.</description>
    <inlineHelpText>Class for which this record&apos;s days/times are specified.</inlineHelpText>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Meeting Times</relationshipLabel>
    <relationshipName>Class_Meeting_Times1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Meeting_Time__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <formula>Class__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Class Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class_Meeting_Time__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Weekdays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Meeting_Time__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <formula>Class__r.Teacher__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teacher</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Class__c/Junction_Class__c.object-meta.xml
<CustomObject>
    <label>Junction-Class</label>
    <nameField>
        <displayFormat>JC-{0000}</displayFormat>
        <label>Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Junction-Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction_Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipName>Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Junction_Class__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipName>Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>GPA</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9th</fullName>
                <default>true</default>
                <label>9th</label>
            </value>
            <value>
                <fullName>10th</fullName>
            </value>
            <value>
                <fullName>11th</fullName>
            </value>
            <value>
                <fullName>12th</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PH.D</fullName>
            </value>
            <value>
                <fullName>Masters</fullName>
            </value>
            <value>
                <fullName>Bachelors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AuraApexController_Test.cls
@isTest
public with sharing class AuraApexController_Test {

    @TestSetup
    static void makeData(){
        //data creation
        Teacher__c teach = new Teacher__c(Name='Banner Banner',Education__c='Masters');
        insert teach;
        Class__c cls = new Class__c(Name='Business',Class_Size__c=10,Teacher__c = teach.id);
        insert cls;
        Time stTm = Time.newInstance(11, 30, 0, 0);
        Time enTm = Time.newInstance(13, 30, 0, 0);
        List<String> dayOfWeek = new List<String>{'Monday','Tuesday','Wednesday','Thursday','Friday'};
        List<Class_Meeting_Time__c> cmt = new List<Class_Meeting_Time__c>();
        for(String day : dayOfWeek){
            cmt.add(new Class_Meeting_Time__c(Day__c=day,Start_Time__c=stTm,End_Time__c=enTm, class__c = cls.id));
        }
        insert cmt;

        List<Student__c> stuList = new List<Student__c>();
        Date dt = Date.newInstance(2021, 6, 3);
        for(integer i = 0;i<2;i++){
            stuList.add(new Student__c(Name='Student'+i,Gpa__c=3,Grade_level__c = '12th',Graduation_Date__c=dt));
        }
        insert stuList;

        List<Junction_Class__c> jcList = new List<Junction_Class__c>();

        for(Student__c stu : stuList){
            jcList.add(new Junction_Class__c(Student__c=stu.id,Class__c=cls.id));
        }

        insert jcList;       

    }

         
        //single case test
        @isTest
        private static void test1() {

            String a = 'abc@123.com';
            String b = 'hello';
            String c = 'world';

            Teacher__c teach = [SELECT Name FROM Teacher__c LIMIT 1];
            Class_Meeting_Time__c cmt = [SELECT Class_Name__c, Day__c FROM Class_Meeting_Time__c LIMIT 1];
            Class__c cls = [SELECT Id FROM Class__c LIMIT 1];

            Test.startTest();
            List<Teacher__c> t = AuraApexController.getTeachers();
            List<Class_Meeting_Time__c> weekly = AuraApexController.getWeeklyMeetingTimes(teach);
            List<Class_Meeting_Time__c> today = AuraApexController.getTodayMeetingTimes(teach, cmt.Day__c);
            List<Class__c> roster = AuraApexController.getRoster(teach);
            List<Junction_Class__c> junction = AuraApexController.getStudents(cls);
            AuraApexController.sendMailMethod(a,b,c);
            Test.stopTest();

            System.assertEquals(t[0].Name, 'Banner Banner');
            System.assertEquals(roster[0].Name, 'Business');
            System.assertNotEquals(junction[0], null);
            System.assertEquals(weekly[0].Class_Name__c, 'Business');
            System.assertEquals(today[0].Class_Name__c, 'Business');
    }
}