force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class_Size__c.field-meta.xml
<CustomField>
    <fullName>Class_Size__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Class Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class_Meeting_Time__c/Class_Meeting_Time__c.object-meta.xml
<CustomObject>
    <label>Class Meeting Time</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Class Meeting Time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Meeting Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Meeting_Time__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Class for which this record&apos;s days/times are specified.</description>
    <inlineHelpText>Class for which this record&apos;s days/times are specified.</inlineHelpText>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Meeting Times</relationshipLabel>
    <relationshipName>Class_Meeting_Times1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Meeting_Time__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Weekdays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Meeting_Time__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <formula>Class__r.Teacher__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teacher</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Class__c/Junction_Class__c.object-meta.xml
<CustomObject>
    <label>Junction-Class</label>
    <nameField>
        <displayFormat>JC-{0000}</displayFormat>
        <label>Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Junction-Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction_Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipName>Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Junction_Class__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipName>Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Approved_for_Gradution__c.field-meta.xml
<CustomField>
    <fullName>Approved_for_Gradution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved for Gradution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>GPA</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9th</fullName>
                <default>true</default>
                <label>9th</label>
            </value>
            <value>
                <fullName>10th</fullName>
            </value>
            <value>
                <fullName>11th</fullName>
            </value>
            <value>
                <fullName>12th</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Has_Graduated__c.field-meta.xml
<CustomField>
    <fullName>Has_Graduated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>checkbox that is flipped when the student has actually graduated</description>
    <label>Graduated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Counselor__c.field-meta.xml
<CustomField>
    <fullName>Student_Counselor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Counselor</label>
    <referenceTo>Student_Counselor__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Counselor__c/Student_Counselor__c.object-meta.xml
<CustomObject>
    <label>Student Counselor</label>
    <nameField>
        <label>Student Counselor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Counselors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Counselor__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PH.D</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Bachelor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PH.D</fullName>
            </value>
            <value>
                <fullName>Masters</fullName>
            </value>
            <value>
                <fullName>Bachelors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentApexController_Test.cls
@isTest
public with sharing class StudentApexController_Test {
    
      
  
    
    @istest
    private static void checkget2day(){
        

        Test.startTest();
        System.assertEquals(System.now().format('EEEE'), StudentScheduleApex.getToday());
        
        
        Test.stopTest();
    }
    @istest
    private static void checkgetstudent(){

        //*
        List<Student__c> s = [SELECT Name, GPA__c, Approved_for_Gradution__c, Grade_Level__c, 
        Graduation_Date__c, Has_Graduated__c,Student_Counselor__c FROM Student__c];
        //*/
    
        Student__c stu = new Student__c(Name = 'test 1', GPA__c = 4.3, Approved_for_Gradution__c = true, Grade_level__c = '11th', 
                        Graduation_Date__c = Date.today(), Has_Graduated__c = false);
        
       
        insert stu;
        
        Test.startTest();
        System.assertEquals(stu.Name, StudentScheduleApex.getStudent().get(0).Name);
        
        
        Test.stopTest();
    }

    @istest
    private static void checkgetsched(){

        Student__c stu = new Student__c(Name = 'test 1', GPA__c = 4.3, Approved_for_Gradution__c = true, Grade_level__c = '11th', 
                        Graduation_Date__c = Date.today(), Has_Graduated__c = false);
         insert stu;
        Teacher__c t = new Teacher__c(Education__c = 'Masters', Name = 'dave');
       
        
        insert t;
        Class__c cls = new Class__c(Name = 'pain', Teacher__c = t.id, Class_Size__c = 400);
        insert cls;

        Class_Meeting_Time__c mt = new Class_Meeting_Time__c(Class__c = cls.Id, Day__c = 'Monday', Start_Time__c = Time.newInstance(10, 0, 0, 0), End_Time__c = Time.newInstance(14, 0, 0, 0) );
        insert mt;

        Junction_Class__c jc = new Junction_Class__c(Student__c = stu.Id, Class__c = cls.Id);
        List<String> s = new List<String>();
        s.add(stu.Name);

       
        
        insert jc;


        System.assert(StudentScheduleApex.getSchedule(s).containsKey(stu.Name));
        
    }
  
}