force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>GPA</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9th</fullName>
                <default>true</default>
                <label>9th</label>
            </value>
            <value>
                <fullName>10th</fullName>
            </value>
            <value>
                <fullName>11th</fullName>
            </value>
            <value>
                <fullName>12th</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Counselor__c.field-meta.xml
<CustomField>
    <fullName>Student_Counselor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Counselor</label>
    <referenceTo>Student_Counselor__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Counselor__c/Student_Counselor__c.object-meta.xml
<CustomObject>
    <label>Student Counselor</label>
    <nameField>
        <label>Student Counselor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Counselors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StudentDataController.cls
public with sharing class StudentDataController {

    @AuraEnabled
    public static List<Student__c> getStudents (){

        List<Student__c> students = [SELECT Id, Name, GPA__c, Grade_Level__c, Student_Counselor__r.Name FROM Student__c];

        return students;

    }

    @AuraEnabled
    public static List<Student__c> getHonorRoll(){
        
        List<Student__c> honor = [SELECT Id, Name, GPA__c, Grade_Level__c FROM Student__c
                                    WHERE GPA__c >= 3.49];

        return honor;

    }
        
}