force-app/main/default/objects/Club__c/Club__c.object-meta.xml
<CustomObject>
    <label>Club</label>
    <nameField>
        <label>Club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club__c/fields/Club_Size__c.field-meta.xml
<CustomField>
    <fullName>Club_Size__c</fullName>
    <label>Club Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Junction_Club__c/Junction_Club__c.object-meta.xml
<CustomObject>
    <label>Junction-Club</label>
    <nameField>
        <displayFormat>JC-{0000}</displayFormat>
        <label>Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Junction-Clubs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction_Club__c/fields/Club__c.field-meta.xml
<CustomField>
    <fullName>Club__c</fullName>
    <label>Club</label>
    <referenceTo>Club__c</referenceTo>
    <relationshipLabel>Junction-Clubs</relationshipLabel>
    <relationshipName>Junction_Clubs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Junction_Club__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Junction-Clubs</relationshipLabel>
    <relationshipName>Junction_Clubs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>GPA</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9th</fullName>
                <default>true</default>
                <label>9th</label>
            </value>
            <value>
                <fullName>10th</fullName>
            </value>
            <value>
                <fullName>11th</fullName>
            </value>
            <value>
                <fullName>12th</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentsVsClubs.cls
public with sharing class StudentsVsClubs {
 
    @AuraEnabled(cacheable=true)
    public static List<Junction_Club__c> fetchStudentsClubs() {
  
        List<Junction_Club__c> stuClubList= [select student__c, club__c, Student__r.Name, Student__r.GPA__c, 
        Student__r.Grade_Level__c, Club__r.Name, club__r.Club_Size__c from Junction_Club__c];
  //    List<Student__c> stuClubList = [select Name, GPA__c, Grade_Level__c from Student__c]  ;
        return stuClubList;
    }
}